/*
 * frm_principal.java
 *
 * Created on 21 de MarÃ§o de 2008, 11:45
 */

package griauletests.firstone;

import java.awt.image.BufferedImage;

import javax.swing.ImageIcon;


/**
 *
 * @author  Matheus Motta
 * 
 */
public class frm_principal extends javax.swing.JFrame {
      //The image of the current fingerprint.
   private BufferedImage fingerprintImage = null;


    public frm_principal() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_log = new javax.swing.JTextArea();
        jtf_nome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_dedos = new javax.swing.JList();
        cbox_mao = new javax.swing.JComboBox();
        view_imagem = new javax.swing.JPanel();
        lb_imgimpressao = new javax.swing.JLabel();
        lb_imgcomgrafo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_ver_dedo = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        rb_vergrafo = new javax.swing.JRadioButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane3 = new javax.swing.JScrollPane();
        tx_sensores = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Foxtrot... O início");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        text_log.setColumns(20);
        text_log.setLineWrap(true);
        text_log.setRows(5);
        text_log.setAutoscrolls(true);
        text_log.setOpaque(false);
        text_log.setSelectionColor(new java.awt.Color(255, 255, 153));
        jScrollPane1.setViewportView(text_log);


        jScrollPane1.setAutoscrolls(true);
        jScrollPane2.setAutoscrolls(true);
        jScrollPane3.setAutoscrolls(true);
        
        jtf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        list_dedos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1 - Polegar", "2 - Dedo Indicador", "3 - Dedo médio", "4 - Dedo Anelar", "5 - Dedo mínimo" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(list_dedos);

        cbox_mao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mão esquerda", "Mão direita" }));
        cbox_mao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_maoActionPerformed(evt);
            }
        });

        view_imagem.setBackground(new java.awt.Color(0, 204, 204));

        lb_imgimpressao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_imgimpressao.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lb_imgimpressao.setMaximumSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout view_imagemLayout = new javax.swing.GroupLayout(view_imagem);
        view_imagem.setLayout(view_imagemLayout);
        view_imagemLayout.setHorizontalGroup(
            view_imagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_imagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_imgimpressao, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lb_imgcomgrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        view_imagemLayout.setVerticalGroup(
            view_imagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_imagemLayout.createSequentialGroup()
                .addGroup(view_imagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(view_imagemLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lb_imgcomgrafo, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
                    .addComponent(lb_imgimpressao, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
                .addContainerGap())
        );

        lb_ver_dedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/branches/griauletests/examples/firstone/images/mao.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_ver_dedo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_ver_dedo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jRadioButton1.setText("Apenas verificar");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Salvar se não existir");

        rb_vergrafo.setText("Ver template");

        tx_sensores.setColumns(20);
        tx_sensores.setRows(5);
        jScrollPane3.setViewportView(tx_sensores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1187, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(31, 31, 31)
                                    .addComponent(jtf_nome))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbox_mao, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jRadioButton1)
                                        .addComponent(jRadioButton2)
                                        .addComponent(rb_vergrafo))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(view_imagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbox_mao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_vergrafo))
                            .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(view_imagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
  

        
    }//GEN-LAST:event_formWindowClosing

    private void jtf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nomeActionPerformed

    private void cbox_maoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_maoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cbox_maoActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioButton1ActionPerformed
    public void limpaForm(){
 
    lb_ver_dedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/branches/griauletests/examples/firstone/images/mao.jpg")));
    
    }
    
   public String get_nome(){
   return this.jtf_nome.getText();  
   } 
      public int get_mao(){
   return this.cbox_mao.getSelectedIndex()+1;  
   }    
      public int get_dedo(){
   return this.list_dedos.getSelectedIndex()+1;  
   }  
      public boolean get_podeverificar(){
      return jRadioButton1.isSelected();
      }
      public boolean get_podesalvar(){
      return jRadioButton2.isSelected();
      }
      
        public boolean get_vertemplate(){
      return rb_vergrafo.isSelected();
      }
      
      
      //setando informacoes no form..   
   public void set_nome(String nome){
  jtf_nome.setText(nome);
   }
   public void updateform(int id_mao,int id_dedo ){
       
       String nomemao="";
   cbox_mao.setSelectedIndex(id_mao-1);
   list_dedos.setSelectedIndex(id_dedo-1);
   switch (id_mao-1)
   {
       case 0 : nomemao="esq"; break;
       case 1 : nomemao="dir"; break;
       default: nomemao=""; break;
   }
   //tornar padrÃ£o depois...
   lb_ver_dedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/branches/griauletests/examples/firstone/images/" +nomemao+"-"+String.valueOf(id_dedo)+".png")));

   
   }
   
   
    public void set_barra( int x){
   jProgressBar1.setValue(x);   
   } 
        public void add_linetosenrorlog( String  line){
   tx_sensores.append(line); 
   } 
   
   
   
   public void set_imagem( BufferedImage img_impressaodigital){
   lb_imgimpressao.setIcon(new ImageIcon(img_impressaodigital));   
   }   
   public void set_imagemcomgrafo( BufferedImage image){
       if(image != null)
   lb_imgcomgrafo.setIcon(new ImageIcon(image));   
       else
           lb_imgcomgrafo.setIcon(null);
   }
  
   
    
public void add_lineInLog(String line){
    text_log.append(line+"\n");   
    
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbox_mao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jtf_nome;
    private javax.swing.JLabel lb_imgcomgrafo;
    private javax.swing.JLabel lb_imgimpressao;
    private javax.swing.JLabel lb_ver_dedo;
    private javax.swing.JList list_dedos;
    private javax.swing.JRadioButton rb_vergrafo;
    private javax.swing.JTextArea text_log;
    private javax.swing.JTextArea tx_sensores;
    private javax.swing.JPanel view_imagem;
    // End of variables declaration//GEN-END:variables
    
}
